#
version: @project.version@
#
server:
  port: 6532
#
spring:
  application:
    name: kafka-dlq-retry
  profiles:
    active: default
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
#
logging:
  level:
    dev.shermende.support.spring.aop.profiling: debug
#
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"