#
version: @project.version@
#
server:
  port: 6532
#
spring:
  application:
    name: kafka-dlq-retry
  profiles:
    active: default
  kafka:
    consumer:
      group-id: ${spring.application.name}
#
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"