# fast start example
# project: kafka-dlq-retry-self-test
version: '3'

services:
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    expose:
      - 9091
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka:9091,LISTENER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop:3.23.0
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9091
    depends_on:
      - kafka
  #
  kafka-dlq-retry:
    build:
      context: ..
      dockerfile: src/main/docker/Dockerfile
    environment:
      spring.profiles.active: self-test
      spring.kafka.producer.bootstrap-servers: kafka:9091
      spring.kafka.consumer.bootstrap-servers: kafka:9091
      dev.shermende.self-test.topic: application
      dev.shermende.self-test.dlq-topic: application.dlq
      dev.shermende.kafka-dlq-retry.consumers[0].topic: application
      dev.shermende.kafka-dlq-retry.consumers[0].dlq-topic: application.dlq
      dev.shermende.kafka-dlq-retry.consumers[0].error-topic: application.error
      dev.shermende.kafka-dlq-retry.consumers[0].delays: 200,300,400
      dev.shermende.kafka-dlq-retry.consumers[0].concurrency: 10
    depends_on:
      - kafka